# Generated by Django 3.2.13 on 2022-06-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('task_des', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
